

# REQUIRED: Name of the standalone module (MUST BE THE SAME AS IT"S DIRECTORY NAME)
MOD_NAME 	?= s_data

# REQUIRED: Names (NOT PAHTS) of all non-test .h files found in the include folder
_HDRS  ?=   binary_search_tree.h \
			destructable.h \
			fixed_queue.h \
			heap.h \
			id_table.h \
			list.h \
			map.h \
			ring.h \
			term_buffer.h \
			wait_queue.h

# REQUIRED: Names (NOT PATHS) of all .c files found in the src folder
_SRCS 		?= id_table.c map.c list.c wait_queue.c ring.c term_buffer.c \
			   fixed_queue.c heap.c binary_search_tree.c

# REQUIRED: Names (NOT PATHS) of all .S files found in the src folder
_ASMS		?= 

# REQUIRED: Names (NOT PAHTS) of all test .h files found in the include test folder
_TEST_HDRS 	?= 	binary_search_tree.h \
				fixed_queue.h \
				heap.h \
				id_table.h \
				list.h \
				map.h \
				ring.h \
				term_buffer.h \
				wait_queue.h

# REQUIRED: Names (NOT PATHS) of all .c files in the test folder
_TEST_SRCS 	?= id_table.c map.c list.c wait_queue.c ring.c term_buffer.c \
			   fixed_queue.c heap.c binary_search_tree.c

-include ../mod_stub.mk

