

# NOTE: This module is freestanding utility code.
# IT DEPENDS ON NOTHING!!!

# REQUIRED: Name of the standalone module (MUST BE THE SAME AS IT"S DIRECTORY NAME)
MOD_NAME 	?= s_util

# REQUIRED: Names (NOT PATHS) of all .c files found in the src folder
_SRCS 		?= str.c misc.c constraints.c rand.c hash.c ps2_scancodes.c \
			   ansi.c

# REQUIRED: Names (NOT PATHS) of all .s files found in the src folder
_ASMS		?= str.s

# REQUIRED: Names (NOT PATHS) of all .c files in the test folder
_TEST_SRCS 	?= str.c \
			   misc.c \
			   ansi.c

-include ../mod_stub.mk

