
# REQUIRED: Name of the standalone module (MUST BE THE SAME AS IT"S DIRECTORY NAME)
MOD_NAME 	?= s_bridge

# REQUIRED: Names (NOT PAHTS) of all non-test .h files found in the include folder
_HDRS  ?=   app.h \
			ctx.h \
			shared_defs.h

# REQUIRED: Names (NOT PATHS) of all .c files found in the src folder
_SRCS 		?= ctx.c app.c

# REQUIRED: Names (NOT PATHS) of all .S files found in the src folder
_ASMS		?= ctx.S

# REQUIRED: Names (NOT PAHTS) of all test .h files found in the include test folder
_TEST_HDRS 	?= 	app.h

# REQUIRED: Names (NOT PATHS) of all .c files in the test folder
_TEST_SRCS 	?= app.c

include ../mod_stub.mk

