
#include "s_util/ps2_scancodes.h"

const char SCS1_TO_ASCII_LC[256] = {
    /*
     * All keys NOT mentioned here should have their entries init'd to 0.
     * (Meaning they have no ascii equivelant)
     */

    [SCS1_1] = '1',
    [SCS1_2] = '2',
    [SCS1_3] = '3',
    [SCS1_4] = '4',
    [SCS1_5] = '5',
    [SCS1_6] = '6',
    [SCS1_7] = '7',
    [SCS1_8] = '8',
    [SCS1_9] = '9',
    [SCS1_0] = '0',
    [SCS1_MINUS] = '-',
    [SCS1_EQUALS] = '=',
    [SCS1_Q] = 'q',
    [SCS1_W] = 'w',
    [SCS1_E] = 'e',
    [SCS1_R] = 'r',
    [SCS1_T] = 't',
    [SCS1_Y] = 'y',
    [SCS1_U] = 'u',
    [SCS1_I] = 'i',
    [SCS1_O] = 'o',
    [SCS1_P] = 'p',
    [SCS1_LBRACKET] = '[',
    [SCS1_RBRACKET] = ']',
    [SCS1_A] = 'a',
    [SCS1_S] = 's',
    [SCS1_D] = 'd',
    [SCS1_F] = 'f',
    [SCS1_G] = 'g',
    [SCS1_H] = 'h',
    [SCS1_J] = 'j',
    [SCS1_K] = 'k',
    [SCS1_L] = 'l',
    [SCS1_SEMICOLON] = ';',
    [SCS1_APOSTROPHE] = '\'',
    // [SCS1_GRAVE] = '', Unsure what this maps to on a newer keyboard.
    [SCS1_BACKSLASH] = '\\',
    [SCS1_Z] = 'z',
    [SCS1_X] = 'x',
    [SCS1_C] = 'c',
    [SCS1_V] = 'v',
    [SCS1_B] = 'b',
    [SCS1_N] = 'n',
    [SCS1_M] = 'm',
    [SCS1_COMMA] = ',',
    [SCS1_PERIOD] = '.',
    [SCS1_SLASH] = '/',
    [SCS1_KP_ASTERISK] = '*',
    [SCS1_SPACE] = ' ',
    [SCS1_KP_7] = '7',
    [SCS1_KP_8] = '8',
    [SCS1_KP_9] = '9',
    [SCS1_KP_MINUS] = '-' ,
    [SCS1_KP_4] = '4',
    [SCS1_KP_5] = '5',
    [SCS1_KP_6] = '6',
    [SCS1_KP_PLUS] = '+',
    [SCS1_KP_1] = '1',
    [SCS1_KP_2] = '2',
    [SCS1_KP_3] = '3',
    [SCS1_KP_0] = '0',
    [SCS1_KP_PERIOD] = '.',
};

const char SCS1_TO_ASCII_UC[256] = {

    [SCS1_1] = '!',
    [SCS1_2] = '@',
    [SCS1_3] = '#',
    [SCS1_4] = '$',
    [SCS1_5] = '%',
    [SCS1_6] = '^',
    [SCS1_7] = '&',
    [SCS1_8] = '*',
    [SCS1_9] = '(',
    [SCS1_0] = ')',
    [SCS1_MINUS] = '_',
    [SCS1_EQUALS] = '+',
    [SCS1_Q] = 'Q',
    [SCS1_W] = 'W',
    [SCS1_E] = 'E',
    [SCS1_R] = 'R',
    [SCS1_T] = 'T',
    [SCS1_Y] = 'Y',
    [SCS1_U] = 'U',
    [SCS1_I] = 'I',
    [SCS1_O] = 'O',
    [SCS1_P] = 'P',
    [SCS1_LBRACKET] = '{',
    [SCS1_RBRACKET] = '}',
    [SCS1_A] = 'A',
    [SCS1_S] = 'S',
    [SCS1_D] = 'D',
    [SCS1_F] = 'F',
    [SCS1_G] = 'G',
    [SCS1_H] = 'H',
    [SCS1_J] = 'J',
    [SCS1_K] = 'K',
    [SCS1_L] = 'L',
    [SCS1_SEMICOLON] = ':',
    [SCS1_APOSTROPHE] = '"',
    // [SCS1_GRAVE] = '', Unsure what this maps to on a newer keyboard.
    [SCS1_BACKSLASH] = '|',
    [SCS1_Z] = 'Z',
    [SCS1_X] = 'X',
    [SCS1_C] = 'C',
    [SCS1_V] = 'V',
    [SCS1_B] = 'B',
    [SCS1_N] = 'N',
    [SCS1_M] = 'M',
    [SCS1_COMMA] = '<',
    [SCS1_PERIOD] = '>',
    [SCS1_SLASH] = '?',

    // The below keys have equal "uppercase" and "lowercase" values.

    [SCS1_KP_ASTERISK] = '*',
    [SCS1_SPACE] = ' ',
    [SCS1_KP_7] = '7',
    [SCS1_KP_8] = '8',
    [SCS1_KP_9] = '9',
    [SCS1_KP_MINUS] = '-' ,
    [SCS1_KP_4] = '4',
    [SCS1_KP_5] = '5',
    [SCS1_KP_6] = '6',
    [SCS1_KP_PLUS] = '+',
    [SCS1_KP_1] = '1',
    [SCS1_KP_2] = '2',
    [SCS1_KP_3] = '3',
    [SCS1_KP_0] = '0',
    [SCS1_KP_PERIOD] = '.',
};
