
# REQUIRED
#
# The name of this application. MUST be the same as this apps directory name.
APP_NAME ?= Test

# REQUIRED
#
# The names of all .c files within `src/apps/$(APP_NAME)`
_SRCS ?= app_main.c

-include ../app_stub.mk
