

# REQUIRED: Name of the standalone module (MUST BE THE SAME AS IT"S DIRECTORY NAME)
MOD_NAME 	?= k_sys

# REQUIRED: Names (NOT PATHS) of all .c files found in the src folder
_SRCS 		?= gdt.c idt.c intr.c page.c

# REQUIRED: Names (NOT PATHS) of all .s files found in the src folder
_ASMS		?= io.s page.s gdt.s idt.s intr.s debug.s

# REQUIRED: Names (NOT PATHS) of all .c files in the test folder
_TEST_SRCS 	?= test.c

-include ../mod_stub.mk

