include ../mod_header_stub.mk

# REQUIRED: Name of the standalone module (MUST BE THE SAME AS IT"S DIRECTORY NAME)
MOD_NAME 	?= u_concur

# REQUIRED: Names (NOT PAHTS) of all non-test .h files found in the include folder
_HDRS  		?= mutex.h

# REQUIRED: Names (NOT PATHS) of all .c files found in the src folder
_SRCS 		?= mutex.c

# REQUIRED: Names (NOT PATHS) of all .S files found in the src folder
_ASMS		?= 

# REQUIRED: Names (NOT PAHTS) of all test .h files found in the include test folder
_TEST_HDRS 	?= mutex.h

# REQUIRED: Names (NOT PATHS) of all .c files in the test folder
_TEST_SRCS 	?= mutex.c

include ../mod_stub.mk

