

# NOTE: This module is freestanding utility code.
# IT DEPENDS ON NOTHING!!!

# REQUIRED: Name of the standalone module (MUST BE THE SAME AS IT"S DIRECTORY NAME)
MOD_NAME 	?= s_elf

# REQUIRED: Names (NOT PATHS) of all .c files found in the src folder
_SRCS 		?= elf32.c

# REQUIRED: Names (NOT PATHS) of all .s files found in the src folder
_ASMS		?=

# REQUIRED: Names (NOT PATHS) of all .c files in the test folder
_TEST_SRCS 	?= elf32.c

-include ../mod_stub.mk

