

# NOTE: This module is freestanding utility code.
# IT DEPENDS ON NOTHING!!!

# REQUIRED: Name of the standalone module (MUST BE THE SAME AS IT"S DIRECTORY NAME)
MOD_NAME 	?= fstndutil

# REQUIRED: Names (NOT PATHS) of all .c files found in the src folder
_SRCS 		?= str.c

# REQUIRED: Names (NOT PATHS) of all .s files found in the src folder
_ASMS		?= 

# REQUIRED: Names (NOT PATHS) of all .c files in the test folder
_TEST_SRCS 	?= test.c str.c

-include ../mod_stub.mk

